#!/usr/bin/env python3
"""Add blog posts 10-24 to lib/blog.ts"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOG_TS = ROOT / "lib" / "blog.ts"

def para(*s): return " ".join(s)
def section(title, *paragraphs, level=2):
    return f"\n{'#'*level} {title}\n\n" + "\n\n".join(paragraphs)
def expand(points):
    blocks = []
    for title, paras in points:
        blocks.append(section(title, *[para(*p) if isinstance(p, tuple) else p for p in paras]))
    return blocks
def make_body(slug, intro, sections, projects, blogs, takeaway, kit_line):
    lines = [intro, f"\n![Cover](/api/blog-covers/{slug})"] + sections
    proj = "\n".join(f"- **[{p['name']}](/projects/{p['slug']})** — {p['desc']}" for p in projects)
    bl = " ".join(f"[{b['name']}](/blog/{b['slug']})" for b in blogs)
    lines += [section("Related reading", para(f"See also {bl}.")), section("Project kits", proj),
              f"\n**Takeaway:** {takeaway} {kit_line}"]
    return "`" + "\n".join(lines) + "`"

POSTS = [
    {"slug":"hybrid-search-rag-explained","title":"Hybrid search in RAG: why keyword + vector beats either alone","excerpt":"Pure vector search misses exact IDs and dates. Learn how BM25 plus embeddings and reciprocal rank fusion fix the blind spots in student RAG projects.","category":"Architecture","readTime":"9 min read","date":"2026-04-05","intro":para("Pure vector search is the default in RAG tutorials — and it is the reason many student demos fail on real questions.","When a user asks for 'Section 4.2 on page 87' or 'Q3 2024 revenue for Project Apollo', embeddings treat similar phrases as interchangeable.","Hybrid search runs keyword matching alongside semantic search, then merges rankings.","That single design choice is often the difference between a viva pass and an awkward silence."), "points":[("What pure vector search misses",[("Embeddings encode meaning, not spelling.","Two chunks about different years or project codes can sit adjacent in vector space.","Students discover this live when the examiner asks a precise factual question and the wrong chunk appears."),("Keyword search (BM25) catches exact tokens: years, section numbers, SKUs, names.","Vector search catches paraphrases: 'revenue growth' vs 'sales increased'.","You need both.")]),("How hybrid retrieval works",[("Step 1: embed the query and retrieve top-N by cosine similarity.","Step 2: tokenize the query and run BM25 over the same chunk index.","Step 3: merge lists with Reciprocal Rank Fusion (RRF) — each chunk gets score 1/(k+rank) from each list, summed.","Chunks that rank well on both lists rise to the top."),("RRF avoids normalizing incompatible scores between BM25 and cosine distance.","k is typically 60; you do not need to tune it heavily for a final year project.")]),("When to mention this in your viva",[("Say: 'We use hybrid retrieval because our users ask both conceptual and exact-match questions.'","Demo: ask a question with a specific year in the source vs a paraphrased summary question.","Both should retrieve correct chunks in a well-tuned system.")]),("Implementation notes for students",[("Libraries: rank_bm25 or Elasticsearch for keyword; FAISS for vectors.","Index the same chunks in both systems with shared IDs.","Log retrieved chunks during testing — you will see when hybrid saves you.")])], "projects":[{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"ships with hybrid retrieval enabled."},{"slug":"chat-with-youtube","name":"Chat with YouTube","desc":"uses hybrid search for timestamp-accurate answers."}],"blogs":[{"slug":"how-rag-works","name":"How RAG works"},{"slug":"faiss-vs-pinecone-student-projects","name":"FAISS vs Pinecone"}],"takeaway":"Hybrid search fixes the exact-match blind spot in vector RAG — implement it and explain RRF in your report.","kit_line":"Both RAG kits include hybrid retrieval out of the box."},
    {"slug":"streamlit-final-year-ai-demos","title":"Why Streamlit is the best demo stack for AI final year projects","excerpt":"React takes weeks; Streamlit gets your RAG or analytics demo in front of examiners in days. Here is how to structure a Streamlit app for viva-ready polish.","category":"Architecture","readTime":"8 min read","date":"2026-04-15","intro":para("Examiners judge what they can see running.","Streamlit lets you ship upload widgets, chat history, and charts in Python — the same language as your ML pipeline.","You are not learning JSX, state management, and a separate API layer while also debugging embeddings.","For final year timelines, that tradeoff is rational, not lazy."), "points":[("Streamlit vs React for AI demos",[("Streamlit: single Python file, hot reload, built-in file uploader and chat components.","React: better for production UX, but 2-3x longer to reach the same demo if you are new to frontend.","For viva: Streamlit wins on time-to-demo."),("Use React MERN kits when the project *is* the web app — library, hotel, ecommerce.","Use Streamlit when the project *is* the AI pipeline.")]),("Structuring a viva-ready Streamlit app",[("Sidebar: API key input, model settings, clear session button.","Main area: upload → processing spinner → chat or results.","Always show citations or generated code — traceability impresses panels.","Add st.expander for 'Retrieved chunks' so examiners see retrieval working.")]),("Common Streamlit mistakes",[("No loading state during embedding — panel thinks it crashed.","Hard-coded paths — demo fails on examiner laptop.","No error message when API key missing.","Fix all three before submission.")]),("Deployment for demo day",[("Run locally with requirements.txt pinned.","Optional: Streamlit Community Cloud for backup URL.","Carry offline screenshots as last resort.")])], "projects":[{"slug":"chat-with-data","name":"Chat with Data","desc":"Streamlit + pandas + Plotly demo."},{"slug":"resume-jd-matcher","name":"Resume / JD Matcher","desc":"radar charts and score breakdown in Streamlit."}],"blogs":[{"slug":"three-patterns-for-ai-projects","name":"three AI patterns"}],"takeaway":"Streamlit keeps AI projects demo-ready fast — structure sidebar, main flow, and citation expanders for viva impact.","kit_line":"All AI kits use Streamlit with viva-friendly layouts."},
    {"slug":"defending-chat-with-pdf-viva","title":"Defending a Chat with PDF project in viva — questions and model answers","excerpt":"Panel-ready answers for PDF parsing, chunking, hybrid retrieval, page citations, and hallucination control in document Q&A projects.","category":"Viva Prep","readTime":"10 min read","date":"2026-04-22","intro":para("Chat with PDF is the most common RAG final year project in 2026.","Examiners have seen ten versions — they will not ask 'what is AI'.","They will ask why your chunk size, why page citations, and what happens on scanned PDFs.","Prepare these answers verbatim."), "points":[("Opening pitch (30 seconds)",[("Our system lets users upload a text PDF, indexes it with hybrid retrieval, and answers questions with page-number citations.","Hallucination is reduced by restricting answers to retrieved context only.")]),("PDF parsing questions",[("Q: Which library parses PDFs? A: pymupdf4llm / PyMuPDF — extracts text per page while preserving page boundaries for citations.","Q: Scanned PDFs? A: Not supported without OCR; our scope is text-based PDFs — honest limitation.")]),("Retrieval questions",[("Q: Why hybrid search? A: Vector alone misses exact section numbers; BM25 catches them.","Q: Chunk size? A: ~500 tokens with overlap — balances context and precision.")]),("Citation questions",[("Q: How do you know page 12? A: Chunk metadata stores source page from parser; UI displays it with every answer.","Demo this live — strongest viva moment.")]),("Failure scenarios",[("Empty upload, corrupted PDF, question outside document — system should say 'not found', not invent.")])], "projects":[{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"full viva bank included."},{"slug":"chat-with-youtube","name":"Chat with YouTube","desc":"compare PDF vs video citation pipeline."}],"blogs":[{"slug":"viva-questions-rag-projects","name":"20 RAG viva questions"}],"takeaway":"Know parsing, hybrid retrieval, citation metadata, and three failure cases cold.","kit_line":"Chat with PDF kit includes cheat sheet and pitch script."},
    {"slug":"defending-chat-with-youtube-viva","title":"Defending Chat with YouTube in viva — transcript, timestamps, and fallback","excerpt":"How to explain caption extraction, Whisper fallback, chunk-to-timestamp mapping, and clickable citations when your project is video Q&A.","category":"Viva Prep","readTime":"10 min read","date":"2026-05-02","intro":para("Video RAG adds one layer PDF projects do not have: time.","Every answer must cite mm:ss and jump the player there.","Examiners will ask how you get transcripts when captions are disabled.","Have a three-layer fallback story ready."), "points":[("Transcript pipeline",[("Layer 1: youtube-transcript-api for official captions.","Layer 2: yt-dlp for auto-generated captions.","Layer 3: Groq Whisper on downloaded audio when captions missing.","This ordering minimizes cost and latency.")]),("Timestamp citations",[("Each chunk stores start_time and video_id.","UI renders clickable timestamp; JavaScript seeks embedded player.","Explain this is metadata from chunking, not LLM guesswork.")]),("Multi-video sessions",[("Optional feature: index multiple URLs; retrieval returns video_id in metadata.","Good viva differentiator if implemented.")]),("Comparison to PDF RAG",[("Same embed-retrieve-generate core; ingestion differs.","Shows you understand modular architecture.")])], "projects":[{"slug":"chat-with-youtube","name":"Chat with YouTube","desc":"complete transcript fallback chain."},{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"baseline RAG for comparison."}],"blogs":[{"slug":"defending-chat-with-pdf-viva","name":"defending Chat with PDF"}],"takeaway":"Explain caption → fallback → chunk → timestamp citation chain without hand-waving.","kit_line":"Chat with YouTube kit documents every fallback layer."},
    {"slug":"chat-with-data-viva-questions","title":"Chat with Data viva prep — text-to-code, safety, and retry logic","excerpt":"Expect questions on pandas code generation, sandboxing, multi-sheet Excel joins, and automatic retry when the LLM hallucinates column names.","category":"Viva Prep","readTime":"9 min read","date":"2026-05-10","intro":para("Chat with Data is not RAG — the LLM writes code, not retrieves paragraphs.","Examiners who know the difference will respect you; those who do not need a clear 30-second distinction.","Prepare for security, retry logic, and showing generated code in the UI."), "points":[("Architecture distinction",[("RAG finds existing text; text-to-code computes new answers from structured data.","Schema summary + sample rows go to LLM; pandas/Plotly code executes; chart or number returns.")]),("Safety questions",[("Q: Arbitrary code execution risk? A: Restricted environment — no network, limited imports, timeout.","Q: Malicious upload? A: File size limits, parse-only with pandas, no shell commands.")]),("Retry loop",[("If code throws KeyError on column name, pass traceback back to LLM for fix — up to 2 retries.","Demo a deliberate wrong column to show recovery.")]),("Multi-sheet Excel",[("Each sheet becomes DataFrame; LLM writes joins when question spans sheets.","Strong viva demo: ask cross-sheet aggregation.")])], "projects":[{"slug":"chat-with-data","name":"Chat with Data","desc":"text-to-code with retry."},{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"contrast with RAG architecture."}],"blogs":[{"slug":"three-patterns-for-ai-projects","name":"three AI patterns"}],"takeaway":"Position as text-to-code, explain sandbox + retry, demo cross-sheet Excel question.","kit_line":"Chat with Data includes sample datasets for demo."},
    {"slug":"resume-jd-matcher-explainable-scoring","title":"Explainable scoring in Resume/JD Matcher — why black-box LLM grades fail","excerpt":"Break down the four weighted components — skills, semantic fit, experience, education — and why deterministic scoring beats asking the LLM for one number.","category":"Architecture","readTime":"9 min read","date":"2026-05-18","intro":para("Asking an LLM 'score this resume 0-100' produces a number with no audit trail.","Examiners and users cannot trust it.","Extract-Score-Generate splits the pipeline: LLM extracts structured fields, your code computes weighted scores, LLM explains gaps.","Every point on the radar chart traces to a formula you can show on a whiteboard."), "points":[("Four components",[("Skill match: overlap between JD required skills and resume skills, with synonym normalization.","Semantic fit: embedding similarity between resume summary and JD description.","Experience: years vs required range.","Education: degree level match.","Weights sum to 100 — document them in report Chapter 4.")]),("Why not pure LLM scoring",[("Non-reproducible, no component breakdown, fails academic rigor.","Deterministic formula same input → same output — testable.")]),("Visualization",[("Radar chart makes viva demo intuitive.","Missing skills list drives improvement suggestions.")]),("Viva questions",[("Walk through formula for one component with example numbers.","Explain synonym map: ML = Machine Learning.")])], "projects":[{"slug":"resume-jd-matcher","name":"Resume / JD Matcher","desc":"full scoring methodology in report."},{"slug":"chat-with-data","name":"Chat with Data","desc":"another non-RAG AI pattern."}],"blogs":[{"slug":"three-patterns-for-ai-projects","name":"extract-score-generate pattern"}],"takeaway":"Decompose score into named weighted components — auditable beats opaque.","kit_line":"Resume/JD Matcher documents every weight and formula."},
    {"slug":"mern-library-rbac-viva","title":"Library Management System viva — RBAC, audit log, and generic CRUD","excerpt":"Answer role middleware, librarian vs member permissions, loan lifecycle, and why a generic CRUD engine matters in MERN final year projects.","category":"Viva Prep","readTime":"10 min read","date":"2026-05-28","intro":para("Library systems are common — examiners dig into RBAC when the topic is familiar.","Three roles: admin, librarian, member.","Each sees different routes and data.","Generic CRUD engine is your architectural talking point."), "points":[("RBAC flow",[("JWT on login → payload contains role.","requireRole middleware checks route access.","Member cannot issue books; librarian cannot delete audit entries.")]),("Loan lifecycle",[("Issue decrements availability; return restores.","Overdue logic optional enhancement.")]),("Audit log",[("Every create/update/delete logged with userId and timestamp.","Admin-only view — accountability story.")]),("Generic CRUD engine",[("New entity = schema file + routes registered.","Viva gold: 'We added MaintenanceRecords without new React pages — schema-driven forms.'")])], "projects":[{"slug":"library-management-system","name":"Library Management System","desc":"RBAC + audit + CRUD engine."},{"slug":"hotel-booking-system","name":"Hotel Booking System","desc":"same platform, different domain."}],"blogs":[{"slug":"hotel-booking-system-architecture","name":"hotel booking architecture"}],"takeaway":"Explain JWT role middleware, loan rules, and schema-driven CRUD as your depth markers.","kit_line":"Library kit includes RBAC diagrams and viva bank."},
    {"slug":"hotel-booking-system-architecture","title":"Hotel booking system architecture — availability, pricing, and custom routes","excerpt":"Why booking breaks out of generic CRUD: server-side total calculation, room occupancy sync, and three-role access for guests and front desk.","category":"Architecture","readTime":"9 min read","date":"2026-06-05","intro":para("Hotel booking looks like CRUD until dates and money enter.","Total = nights × rate must compute server-side.","Room status must flip occupied on check-in and available on checkout.","This entity uses custom route handlers — a deliberate teaching choice."), "points":[("Three roles",[("Guest: browse, book own stays, cancel confirmed.","Front-desk: manage all bookings and guests.","Admin: full access plus audit log and hard deletes.")]),("Availability logic",[("Before confirm: check room free for date range.","On confirm: mark occupied; on checkout/cancel: mark available.","Race conditions: mention optimistic locking or transaction if asked.")]),("Server-side pricing",[("Client sends dates and roomId only; server loads rate and computes total.","Never trust client-submitted price — classic security viva question.")]),("Platform reuse",[("Auth, RBAC, notifications shared with library and restaurant kits.","Domain logic differs in booking.controller — modular monolith pattern.")])], "projects":[{"slug":"hotel-booking-system","name":"Hotel Booking System","desc":"custom booking routes documented."},{"slug":"restaurant-management-system","name":"Restaurant Management System","desc":"similar order lifecycle pattern."}],"blogs":[{"slug":"mern-library-rbac-viva","name":"library RBAC viva"}],"takeaway":"Booking is custom logic on shared MERN platform — emphasize server-side totals and occupancy sync.","kit_line":"Hotel kit includes ER diagram and sequence diagram for booking flow."},
    {"slug":"restaurant-management-system-guide","title":"Restaurant management system — order lifecycle and server-side totals","excerpt":"Guide to dine-in table tracking, kitchen status flow, and why menu prices must never come from the client in MERN project submissions.","category":"Guides","readTime":"8 min read","date":"2026-06-15","intro":para("Restaurant systems teach state machines and trust boundaries.","An order moves placed → preparing → served → completed.","Tables free automatically when orders complete.","Prices come from menu lookup on the server — always."), "points":[("Order state machine",[("Each transition validated server-side.","Staff advance status; customer sees read-only tracking.","Diagram this in report — examiners love state machines.")]),("Table sync",[("Dine-in orders bind to tableId.","Completion sets table available — prevents double seating.")]),("Security story",[("Malicious client could POST total: 1 rupee.","Server recomputes from menu item IDs and quantities.","Memorize this answer.")]),("Customer self-service",[("Browse menu, place takeaway or dine-in, track status.","Demo both staff and customer logins in viva.")])], "projects":[{"slug":"restaurant-management-system","name":"Restaurant Management System","desc":"full order lifecycle."},{"slug":"hotel-booking-system","name":"Hotel Booking System","desc":"parallel MERN domain kit."}],"blogs":[{"slug":"vehicle-fleet-management-final-year","name":"fleet management guide"}],"takeaway":"State machine + server-side pricing = defensible restaurant MERN project.","kit_line":"Restaurant kit seeds menu and tables for instant demo."},
    {"slug":"vehicle-fleet-management-final-year","title":"Vehicle fleet management for final year — trips, drivers, and record-level RBAC","excerpt":"Assign vehicles, track trip lifecycle, and explain record-level permission checks where drivers update only their own trips.","category":"Guides","readTime":"9 min read","date":"2026-06-25","intro":para("Fleet management is the richest RBAC example in our MERN lineup.","Dispatchers assign trips; drivers see only theirs.","Record-level check: trip.driverUserId === req.user.userId inside handler, not just role middleware.","That distinction wins vivas."), "points":[("Roles",[("Admin: all entities and audit.","Dispatcher: create trips, assign vehicle and driver.","Driver: list and update status on own trips only.")]),("Vehicle availability",[("Assign trip → vehicle status on-trip.","Complete trip → available again.")]),("Record-level security",[("Role middleware says 'is driver'; handler says 'is THIS driver'.","Explain difference with diagram.")]),("Maintenance records",[("Separate CRUD entity per vehicle.","Optional report section for fleet upkeep.")])], "projects":[{"slug":"vehicle-fleet-management-system","name":"Vehicle Fleet Management","desc":"record-level RBAC example."},{"slug":"library-management-system","name":"Library Management System","desc":"role-only RBAC comparison."}],"blogs":[{"slug":"mern-library-rbac-viva","name":"library RBAC viva"}],"takeaway":"Fleet kit demonstrates record-level ownership — prepare to contrast with role-only middleware.","kit_line":"Fleet kit includes dispatcher and driver demo accounts."},
    {"slug":"razorpay-mern-ecommerce-viva","title":"Razorpay MERN ecommerce viva — payment verification and order flow","excerpt":"HMAC-SHA256 signature verification, test mode keys, order state after payment, and admin catalogue management for ecommerce final year vivas.","category":"Viva Prep","readTime":"10 min read","date":"2026-07-05","intro":para("Payment integration is high risk in vivas — either you explain HMAC or you fail.","Razorpay sends order_id, payment_id, signature to client; server verifies before marking paid.","Never update order status on client callback alone."), "points":[("Checkout flow",[("Server creates Razorpay order with amount in paise.","Client opens Razorpay modal.","On success, client POSTs ids + signature to verify endpoint.")]),("HMAC verification",[("expected = HMAC_SHA256(order_id + '|' + payment_id, secret).","Compare with signature constant-time.","Only then set order paid.")]),("Test mode",[("Razorpay test keys and test UPI/card numbers.","Demo without real money.")]),("Admin features",[("Product CRUD on Cloudinary images.","Order status updates: placed → shipped → delivered.")])], "projects":[{"slug":"mern-ecommerce","name":"MERN E-Commerce","desc":"Razorpay + Redux cart."},{"slug":"library-management-system","name":"Library Management System","desc":"MERN without payments for comparison."}],"blogs":[{"slug":"ai-vs-mern-final-year-project","name":"AI vs MERN"}],"takeaway":"Draw Razorpay verify flow on board; never trust client-side payment success alone.","kit_line":"Ecommerce kit includes test keys setup guide."},
    {"slug":"customize-kit-college-name","title":"How to customize a project kit with your college name and branding","excerpt":"Replace logos, seed data, report cover page, and UI strings so your submission looks institution-specific without rewriting core architecture.","category":"Guides","readTime":"7 min read","date":"2026-07-15","intro":para("Customization is how kits become yours.","Change college name on report cover, favicon, seed data names, and demo accounts.","Examiners notice thoughtful local context — 'Hotel Sunrise Pune' beats 'Hotel ABC'."), "points":[("Report and presentation",[("Swap cover page template fields: college, department, guide.","Update screenshot captions with your institution name.")]),("UI branding",[("Logo in public/ folder, primary color in Tailwind config or Streamlit theme.","Footer: 'Developed as final year project, XYZ College'.")]),("Seed data",[("MongoDB seed: local names, phone formats, currency.","PDF demo: use your syllabus or a public domain doc.")]),("One real feature addition",[("Export PDF report button, email on booking confirm, extra chart — document in implementation chapter.")])], "projects":[{"slug":"hotel-booking-system","name":"Hotel Booking System","desc":"easy seed customization."},{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"swap demo PDF and report title page."}],"blogs":[{"slug":"same-project-differentiate","name":"standing out with same topic"}],"takeaway":"College name, local seed data, and one added feature make a kit submission clearly yours.","kit_line":"All kits ship editable report and deck templates."},
    {"slug":"common-viva-mistakes-cs","title":"10 common viva mistakes CS students make (and how to avoid them)","excerpt":"From reading slides verbatim to claiming 100% accuracy — the failure patterns external examiners see every season.","category":"Viva Prep","readTime":"8 min read","date":"2026-07-25","intro":para("Most vivas are lost on presentation and honesty, not code quality.","Avoid these ten patterns and you are already ahead of half the batch."), "points":[("Mistakes 1-3",[("Reading slides word-for-word — panel stops listening.","Saying 'no limitations' — instantly unbelievable.","Cannot run demo — worse than weak code.")]),("Mistakes 4-6",[("Blaming teammates in external viva.","Guessing architecture instead of saying 'I will check my report'.","No test cases in report.")]),("Mistakes 7-10",[("Buzzwords without definitions: 'we used blockchain AI cloud'.","Demo only happy path.","Arguing with examiner.","Not knowing what's in your own report abstract.")]),("Fix checklist",[("Rehearse demo 5 times.","Memorize 3 limitations.","Read abstract aloud day before.")])], "projects":[{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"includes viva cheat sheet."},{"slug":"mern-ecommerce","name":"MERN E-Commerce","desc":"payment demo script."}],"blogs":[{"slug":"what-examiners-look-for-demo","name":"demo expectations"}],"takeaway":"Rehearse demo, name limitations, explain don't read — three habits that prevent most failures.","kit_line":"Every kit includes viva preparation materials."},
    {"slug":"what-examiners-look-for-demo","title":"What examiners actually look for in your project demo","excerpt":"Not flashy UI — traceability, edge case handling, and you explaining one design decision live while the app runs.","category":"Viva Prep","readTime":"8 min read","date":"2026-08-05","intro":para("The demo is not a trailer.","It is proof you built and understand the system.","Examiners watch whether you navigate confidently, handle a wrong input, and explain one backend decision."), "points":[("Three demo scenarios",[("Happy path: core feature in under 2 minutes.","Edge case: empty input or out-of-scope question — graceful message.","Traceability: show citation, audit log entry, or generated code.")]),("What impresses",[("You typed the scenario without reading script.","You explain server-side validation during MERN demo.","You open retrieved chunks expander during RAG demo.")]),("What fails",[("Long loading with no feedback.","Apologizing for 'small bug' on main feature.","Student silent while video plays.")]),("Timing",[("Leave 3 minutes for examiner questions during demo slot if format allows.")])], "projects":[{"slug":"chat-with-youtube","name":"Chat with YouTube","desc":"timestamp click demo."},{"slug":"vehicle-fleet-management-system","name":"Fleet Management","desc":"driver vs dispatcher login demo."}],"blogs":[{"slug":"final-year-presentation-14-slides","name":"14-slide presentation guide"}],"takeaway":"Three scenarios: success, graceful failure, traceability — rehearsed until boring.","kit_line":"Kits include demo scripts for each scenario."},
    {"slug":"faiss-vs-pinecone-student-projects","title":"FAISS vs Pinecone for student RAG projects — cost, setup, and viva answers","seoTitle":"FAISS vs Pinecone for Student RAG Projects","excerpt":"Local FAISS is free and offline-friendly; Pinecone is managed and scales. Here is what to pick for a final year submission and how to defend the choice.","category":"Architecture","readTime":"8 min read","date":"2026-08-20","intro":para("Vector storage choice is a standard viva question.","FAISS runs on your laptop — no API key, no bill, works in lab with bad Wi-Fi.","Pinecone is hosted — less ops, monthly cost, needs internet.","For most college submissions, FAISS is the rational default."), "points":[("FAISS advantages",[("Free, local, fast for thousands of chunks.","Pairs with sentence-transformers on CPU.","Demo works offline at viva.")]),("Pinecone advantages",[("Managed index, no RAM limit worries at huge scale.","Good if college mandates cloud deployment.","Free tier exists but requires account and network.")]),("Viva answers",[("Q: Why FAISS? A: Zero cost, offline demo, sufficient for single-user academic scale.","Q: Limitations? A: In-memory index resets unless persisted to disk — we save index file after upload.","Q: When Pinecone? A: Multi-tenant production with millions of vectors.")]),("Persistence note",[("Save FAISS index to disk after embedding; reload on app start.","Mention this — shows ops awareness.")])], "projects":[{"slug":"pdf-rag-chat","name":"Chat with PDF","desc":"FAISS-based index."},{"slug":"chat-with-youtube","name":"Chat with YouTube","desc":"same local vector store."}],"blogs":[{"slug":"how-rag-works","name":"How RAG works"},{"slug":"hybrid-search-rag-explained","name":"hybrid search"}],"takeaway":"Pick FAISS for college demos; know persistence and when you'd outgrow it.","kit_line":"AI kits use FAISS with on-disk persistence documented."},
]

def build_post(m):
    body = make_body(m["slug"], m["intro"], expand(m["points"]), m["projects"], m["blogs"], m["takeaway"], m["kit_line"])
    o = [f'  {{', f'    slug: "{m["slug"]}",', f'    title: "{m["title"]}",']
    if m.get("seoTitle"): o.append(f'    seoTitle: "{m["seoTitle"]}",')
    o += [f'    excerpt: "{m["excerpt"]}",', f'    category: "{m["category"]}",', f'    readTime: "{m["readTime"]}",', f'    date: "{m["date"]}",', f'    body: {body},', '  },']
    return "\n".join(o)

def main():
    c = BLOG_TS.read_text()
    if 'slug: "hybrid-search-rag-explained"' in c:
        print("Posts 10-24 already present")
        return
    ins = "\n".join(build_post(p) for p in POSTS)
    c = c.replace("\n];", f"\n{ins}\n];")
    BLOG_TS.write_text(c)
    n = len(re.findall(r'^\s+slug: "', c, re.M))
    print(f"Added {len(POSTS)} posts. Total: {n}")

if __name__ == "__main__":
    main()
